# Generated by Django 4.1.2 on 2023-06-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillas', '0002_remove_producto_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_zapatillas',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
